# spring 配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 服务器配置
server:
  # 端口
  port: 8080